name: ChestBank
main: me.ellbristow.ChestBank.ChestBank
version: 1.0
author: ellbristow
description: >
             Create a private account in a chest, accessible from any other ChestBank.
commands:
  chestbank:
    description: ChestBank command list
    usage: "Please see /chestbank (or /cb) for ChestBank commands"
    aliases: cb
permissions:
  chestbank.*:
    description: Access to all ChestBank permissions
    children:
      chestbank.create: true
      chestbank.remove: true
      chestbank.see: true
      chestbank.use: true
  chestbank.create:
    description: Can create a ChestBank.
  chestbank.remove:
    description: Can remove a ChestBank.
  chestbank.see:
    description: (For Mods) Can access other players accounts.
  chestbank.use:
    description: Can use ChestBanks.
