name: ChestBank
main: me.ellbristow.ChestBank.ChestBank
version: 1.4.4
author: ellbristow
dev-url: http://dev.bukkit.org/server-mods/chestbank
softdepend: [Vault,My Worlds,Multiverse,WhooshingWell]
description: >
             Create a private account in a chest, accessible from any other ChestBank.
commands:
  chestbank:
    description: ChestBank command list
    usage: "Please see /chestbank (or /cb) for ChestBank commands"
    aliases: cb

permissions:
  chestbank.*:
    description: Access to all ChestBank permissions
    children:
      chestbank.info: true
      chestbank.list: true
      chestbank.use.*: true
      chestbank.create.*: true
      chestbank.remove.*: true
      chestbank.see.*: true
      chestbank.free.*: true
      chestbank.ignore.*: true

  chestbank.use.*:
    description: Can use any chestbank on any network
    children:
      chestbank.use: true
      chestbank.use.networks: true
  chestbank.use:
    description: Can use ChestBanks on the default network
  chestbank.use.networks:
    description: Can use ChestBanks on alternative networks

# Command Permissions

  chestbank.create.*:
    description: Can create any chestbank on any network
    children:
      chestbank.create: true
      chestbank.create.networks: true
  chestbank.create:
    description: Can create a ChestBank on the default network
  chestbank.create.networks:
    description: Can create a ChestBank on an alternative networks

  chestbank.info:
    description: Access to the /cb info command

  chestbank.list:
    description: Access to the /cb list command

  chestbank.remove.*:
    description: Can remove any chestbank on any network
    children:
      chestbank.remove: true
      chestbank.remove.networks: true
  chestbank.remove:
    description: Can remove a ChestBank on the default network
  chestbank.remove.networks:
    description: Can remove a ChestBank on an alternative networks

  chestbank.see.*:
    description: Can see anyones chestbank account on any network
    children:
      chestbank.see: true
      chestbank.see.networks: true
  chestbank.see:
    description: (For Mods) Can access other players accounts.
  chestbank.see.networks:
    description: (For Mods) Can access other players network accounts.

# Usage Limit Permissions
# If no .limited permission is specified, player can use the whole ChestBank
# If .limited is present, player observes the limit settings from config.yml

  chestbank.limited.normal:
    description: Uses the "normal" limit
    default: false
  chestbank.limited.elevated:
    description: Uses the "elevated" limit
    default: false
  chestbank.limited.vip:
    description: Uses the "vip" limit
    default: false

# Whitelist/Blacklist Permissions

  chestbank.ignore.*:
    description: Can ignore blacklist and whitelist restrictions
    children:
      chestbank.ignore.whitelist: true
      chestbank.ignore.blacklist: true
  chestbank.ignore.whitelist:
    description: Can ignore whitelist restrictions
  chestbank.ignore.blacklist:
    description: Can ignore blacklist restrictions
    
# Economy Permissions

  chestbank.free.*:
    description: Can create and use chestbanks on any network for free
    children:
      chestbank.free.create.*: true
      chestbank.free.use.*: true
  chestbank.free.create.*:
    description: Can create ChestBanks on any network for free
    children:
      chestbank.free.create: true
      chestbank.free.create.networks: true
  chestbank.free.create:
    description: Can create ChestBanks for free
  chestbank.free.create.networks:
    description: Can create ChestBanks on alternative networks for free
  chestbank.free.use.*:
    description: Can use ChestBanks on any network for free
    children:
      chestbank.free.use: true
      chestbank.free.use.networks: true  
  chestbank.free.use:
    description: Can use ChestBanks for free
  chestbank.free.use:
    description: Can use ChestBanks on alternative networks for free
